server:
  error:
    include-stacktrace: on-param
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliverit?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect